spring.application.name=ensm-auth
server.port=55556

# H2 Database (임시, 실제로는 사용 안 함)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# 로그 파일 경로 (환경 변수로 오버라이드 가능, 기본값은 SystemConfig에서 관리)
logging.file.name=${LOG_PATH_AUTH:/var/log/auth/auth-app.log}
logging.level.org.springframework.web=INFO
logging.level.com.ensm=INFO

server.forward-headers-strategy=framework
server.use-forward-headers=true
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto